
/* Drop Tables */

DROP TABLE RIDER CASCADE CONSTRAINTS;
DROP TABLE SALES CASCADE CONSTRAINTS;
DROP TABLE BASKET CASCADE CONSTRAINTS;
DROP TABLE BOARDREPLY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE LINECOMMENTS CASCADE CONSTRAINTS;
DROP TABLE PLIST CASCADE CONSTRAINTS;
DROP TABLE ITEMS CASCADE CONSTRAINTS;
DROP TABLE MASTER CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BASKET
(
	BNO number NOT NULL,
	ID varchar2(15) NOT NULL,
	INO number NOT NULL,
	AMOUNT number NOT NULL,
	PRIMARY KEY (BNO)
);


CREATE TABLE BOARD
(
	BONO number NOT NULL,
	ID varchar2(15) NOT NULL,
	TITLE nvarchar2(20) NOT NULL,
	CATEGORY varchar2(50) DEFAULT '' NOT NULL,
	BCOUNT nvarchar2(200) DEFAULT '' NOT NULL,
	BCONTENT nvarchar2(200) NOT NULL,
	postDate date DEFAULT SYSDATE,
	PRIMARY KEY (BONO)
);


CREATE TABLE BOARDREPLY
(
	BONO number NOT NULL,
	ADCOMMENT nvarchar2(100),
	ADREPLYDATE date DEFAULT SYSDATE
);


CREATE TABLE ITEMS
(
	INO number NOT NULL,
	ID varchar2(15) NOT NULL,
	INAME nvarchar2(20) NOT NULL,
	INAME2 nvarchar2(50) NOT NULL,
	PRICE varchar2(20) NOT NULL,
	BRAND varchar2(20) NOT NULL,
	CATEGORY varchar2(20) NOT NULL,
	INAME3 nvarchar2(50),
	IMAGE bfile,
	IMAGE2 bfile,
	IPAGE bfile,
	IPAGE2 bfile,
	STOCK varchar2(20),
	HASHTAG varchar2(20),
	DISH number,
	PRIMARY KEY (INO)
);


CREATE TABLE LINECOMMENTS
(
	LNO number NOT NULL,
	ID varchar2(15) NOT NULL,
	INO number NOT NULL,
	LINECOMMENT varchar2(50) NOT NULL,
	LSOCRE number(1) NOT NULL,
	LPOSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (LNO)
);


CREATE TABLE MASTER
(
	MNO number NOT NULL,
	ID varchar2(15) NOT NULL,
	MNAME varchar2(20) NOT NULL,
	MTEL varchar2(13) NOT NULL,
	MADDR1 nvarchar2(5) NOT NULL,
	MADDR2 nvarchar2(50),
	MADDR3 nvarchar2(50),
	MASTERNAME varchar2(10),
	MARTLICENSE varchar2(30),
	PRIMARY KEY (MNO)
);


CREATE TABLE MEMBER
(
	ID varchar2(15) NOT NULL,
	NO number NOT NULL,
	PWD nvarchar2(20) NOT NULL,
	NAME nvarchar2(20) NOT NULL,
	ADDR varchar2(100) NOT NULL,
	TEL varchar2(13) NOT NULL,
	MAIL varchar2(50) NOT NULL,
	BIRTH date DEFAULT SYSDATE,
	PRIMARY KEY (ID)
);


CREATE TABLE PLIST
(
	INO number NOT NULL,
	DELIVERYPAY varchar2(50) NOT NULL,
	PSCORE varchar2(200) NOT NULL,
	COUPON nvarchar2(20),
	PVIEW varchar2(50),
	PBYUCOUNT number(30),
	PTAG nvarchar2(200)
);


CREATE TABLE RIDER
(
	ID varchar2(15) NOT NULL,
	SNO number NOT NULL,
	LICENSE nvarchar2(15) NOT NULL,
	BANKACCOUNT nvarchar2(10) NOT NULL,
	RIDEVEHICLE number(10) NOT NULL
);


CREATE TABLE SALES
(
	SNO number NOT NULL,
	BNO number NOT NULL,
	METHOD number(10) NOT NULL,
	SDATE date DEFAULT SYSDATE,
	PRIMARY KEY (SNO)
);



/* Create Foreign Keys */

ALTER TABLE SALES
	ADD FOREIGN KEY (BNO)
	REFERENCES BASKET (BNO)
;


ALTER TABLE BOARDREPLY
	ADD FOREIGN KEY (BONO)
	REFERENCES BOARD (BONO)
;


ALTER TABLE BASKET
	ADD FOREIGN KEY (INO)
	REFERENCES ITEMS (INO)
;


ALTER TABLE LINECOMMENTS
	ADD FOREIGN KEY (INO)
	REFERENCES ITEMS (INO)
;


ALTER TABLE PLIST
	ADD FOREIGN KEY (INO)
	REFERENCES ITEMS (INO)
;


ALTER TABLE BASKET
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBERS (ID)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBERS (ID)
;


ALTER TABLE ITEMS
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE LINECOMMENTS
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE MASTER
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE RIDER
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE RIDER
	ADD FOREIGN KEY (SNO)
	REFERENCES SALES (SNO)
;


CREATE SEQUENCE NO
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_SALES
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_ITEMS
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_BASKET
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_BOARD
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_LINECOMMENTS
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_MASTER
NOCACHE
NOCYCLE;
