
/* Drop Tables */

DROP TABLE MYPAGE CASCADE CONSTRAINTS;
DROP TABLE RIDER CASCADE CONSTRAINTS;
DROP TABLE BASKET CASCADE CONSTRAINTS;
DROP TABLE LINECOMMENTS CASCADE CONSTRAINTS;
DROP TABLE MART CASCADE CONSTRAINTS;
DROP TABLE ITEMS CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BASKET
(
	BNO number DEFAULT 1 NOT NULL,
	NO number NOT NULL,
	MNO varchar2(2000) NOT NULL UNIQUE,
	INVOICE varchar2(20) NOT NULL,
	PRIMARY KEY (BNO)
);


CREATE TABLE ITEMS
(
	INO nvarchar2(20) NOT NULL,
	IMAGE nvarchar2(100) NOT NULL,
	IMAGE2 ,
	INAME nvarchar2(20) NOT NULL,
	INAME2 nvarchar2(15),
	-- 상품리스트에 들어갈 간략한 설명
	INAME3 nvarchar2(20),
	PRICE varchar2(20) NOT NULL,
	IPAGE nvarchar2(100),
	-- 교환 환불 처리 관련 이미지
	IPAGE2 nvarchar2(500),
	CATEGORY number NOT NULL,
	STOCK number,
	-- ~~을 검색하면 나올 수 있게 설정
	HASHTAG nvarchar2(50),
	DISH float,
	BRAND nvarchar2(20) NOT NULL,
	PRIMARY KEY (INO)
);


CREATE TABLE LINECOMMENTS
(
	LNO number NOT NULL,
	NO number NOT NULL,
	INO nvarchar2(20) NOT NULL,
	LINECOMMENT varchar2(50) NOT NULL,
	LSCORE number NOT NULL,
	LPOSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (LNO)
);


CREATE TABLE MART
(
	MNO varchar2(2000) NOT NULL UNIQUE,
	INO nvarchar2(20) NOT NULL,
	MID nvarchar2(15) NOT NULL UNIQUE,
	MPWD nvarchar2(20) NOT NULL,
	MNAME nvarchar2(15) NOT NULL,
	MADDR nvarchar2(50) NOT NULL,
	MTEL varchar2(15),
	DELIVERYPAY varchar2(10) NOT NULL,
	PRIMARY KEY (MNO)
);


CREATE TABLE MEMBER
(
	NO number NOT NULL,
	ID varchar2(20) NOT NULL UNIQUE,
	PWD nvarchar2(20) NOT NULL,
	NAME nvarchar2(20) NOT NULL,
	ADDR varchar2(100) NOT NULL,
	TEL varchar2(13) NOT NULL,
	MAIL varchar2(50) NOT NULL,
	REGDATE date DEFAULT SYSDATE,
	PRIMARY KEY (NO)
);


CREATE TABLE MYPAGE
(
	BNO number DEFAULT 1 NOT NULL,
	NO number NOT NULL,
	RECODE nvarchar2(2000),
	-- (0=배송준비중,1=배송중,2=배송완료,3=교환/환불)
	DELIVERY number NOT NULL,
	POINT varchar2(10)
);


CREATE TABLE RIDER
(
	BNO number DEFAULT 1 NOT NULL,
	NO number NOT NULL,
	-- ex)운전경력 2년 이상
	LICENSE nvarchar2(15) NOT NULL,
	CARNUM nvarchar2(10) NOT NULL
);



/* Create Foreign Keys */

ALTER TABLE MYPAGE
	ADD FOREIGN KEY (BNO)
	REFERENCES BASKET (BNO)
;


ALTER TABLE RIDER
	ADD FOREIGN KEY (BNO)
	REFERENCES BASKET (BNO)
;


ALTER TABLE LINECOMMENTS
	ADD FOREIGN KEY (INO)
	REFERENCES ITEMS (INO)
;


ALTER TABLE MART
	ADD FOREIGN KEY (INO)
	REFERENCES ITEMS (INO)
;


ALTER TABLE BASKET
	ADD FOREIGN KEY (MNO)
	REFERENCES MART (MNO)
;


ALTER TABLE BASKET
	ADD FOREIGN KEY (NO)
	REFERENCES MEMBER (NO)
;


ALTER TABLE LINECOMMENTS
	ADD FOREIGN KEY (NO)
	REFERENCES MEMBER (NO)
;


ALTER TABLE MYPAGE
	ADD FOREIGN KEY (NO)
	REFERENCES MEMBER (NO)
;


ALTER TABLE RIDER
	ADD FOREIGN KEY (NO)
	REFERENCES MEMBER (NO)
;



/* Comments */

COMMENT ON COLUMN ITEMS.INAME3 IS '상품리스트에 들어갈 간략한 설명';
COMMENT ON COLUMN ITEMS.IPAGE2 IS '교환 환불 처리 관련 이미지';
COMMENT ON COLUMN ITEMS.HASHTAG IS '~~을 검색하면 나올 수 있게 설정';
COMMENT ON COLUMN MYPAGE.DELIVERY IS '(0=배송준비중,1=배송중,2=배송완료,3=교환/환불)';
COMMENT ON COLUMN RIDER.LICENSE IS 'ex)운전경력 2년 이상';



